name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "AKIAT6PXEOIZM5TTBEUN"
          aws-secret-access-key: "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"
          aws-region: us-east-1
        env:
          aws-access-key-id: "AKIAT6PXEOIZM5TTBEUN"
          aws-secret-access-key: "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"
        run:
            echo  ${{ secrets.AWS_ACCESS_KEY_ID }}
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: deploy
        run: |
          npx ncc build index.ts
          zip -j deploy.zip ./dist/*
          aws lambda update-function-code --function-name=myFirstLambda --zip-file=fileb://deploy.zip
